name: "Attic Watch and Push"
description: "Composite action pushes results after the job completes. Needs prior attic-cache action to have executed successfully."

inputs:
  cache_repository:
    description: "Cache repository to use with attic"
    required: true

runs:
  using: "composite"
  steps:
    - name: Attic Push Results
      shell: "nix shell nixpkgs#attic-client --command {0}"
      run: |
        attic push "${{ inputs.cache_repository }}" "./result" # TODO: Make this smarter
