general {
        colors = true
        interval = 3
}

order += "disk /home/fabian/data"
order += "ipv6"
order += "run_watch VPN"
order += "wireless wlp3s0"
order += "ethernet em0"
order += "ethernet em1"
order += "battery 0"
order += "load"
order += "time"

disk "/home/fabian/data" {
	format = "%free"
}

ipv6 {
	format_up = "%ip"
	format_down = "IPv6"
}

wireless wlp3s0 {
        format_up = "W: %ip (%quality %essid)"
        format_down = "wlp3s0"
}

ethernet em1 {
        # if you use %speed, i3status requires root privileges
        format_up = "em1: %ip"
        format_down = "em1"
}

ethernet em0 {
	format_up = "em0: %ip"
	format_down = "em0"
}

battery 0 {
        format = "%status %percentage %remaining"
}

run_watch VPN {
        pidfile = "/var/run/vpnc/defaultroute"
}

time {
        format = "%Y-%m-%d %H:%M:%S"
}

load {
        format = "%1min"
}
