general {
        colors = true
        interval = 3
}

order += "ipv6"
order += "run_watch VPN"
order += "wireless wlan0"
order += "ethernet wwan0"
order += "ethernet em0"
order += "ethernet em1"
order += "battery 0"
order += "load"
order += "time"

ipv6 {
	format_up = "%ip"
	format_down = "IPv6"
}

wireless wlan0 {
        format_up = "W: %ip (%quality %essid)"
        format_down = "wlan0"
}

ethernet wwan0 {
	format_up = "Ww: %ip"
	format_down ="wwan0"
}

ethernet em1 {
        # if you use %speed, i3status requires root privileges
        format_up = "em1: %ip"
        format_down = "em1"
}

ethernet em0 {
	format_up = "em0: %ip"
	format_down = "em0"
}

battery 0 {
        format = "%status %percentage %remaining"
}

run_watch VPN {
        pidfile = "/var/run/vpnc/pid"
}

time {
        format = "%Y-%m-%d %H:%M:%S"
}

load {
        format = "%1min"
}
