general {
        colors = true
        interval = 5
}

order += "disk /home/fabian/data"
order += "disk /"
order += "volume master"
order += "run_watch VPN"
order += "ipv6"
order += "wireless wlp3s0"
order += "ethernet enp0s25"
order += "ethernet wwp0s29u1u4i6"
order += "load"
order += "cpu_temperature 0"
order += "battery 0"
order += "time"

volume master {
	format = "♪%volume"
	format_muted = "♪∅(%volume)"
	device = "default"
	mixer = "Master"
	mixer_idx = 0
}

ipv6 {
	format_up = "v6"
	format_down = "v6"
	color_bad = "#884444"
}

wireless wlp3s0 {
        format_up = "W: %ip (%quality %essid)"
        format_down = "wlp3s0"
	color_bad = "#884444"
}

ethernet enp0s25 {
        # if you use %speed, i3status requires root privileges
        format_up = "enp0s25: %ip"
        format_down = "enp0s25"
	color_bad = "#884444"
}

ethernet wwp0s29u1u4i6 {
	format_up = "ww0s29: %ip"
	format_down = "ww0s29"
	color_bad = "#884444"
}

battery 0 {
# %remaining -> not realisistic lasting time?
        format = "%status %percentage %remaining %emptytime"
	status_bat = B
	status_chr = "B+"
	last_full_capacity = true
	hide_seconds = true
}

run_watch VPN {
        pidfile = "/var/run/vpnc/defaultroute"
	format = "%title"
	color_bad = "#884444"
}

time {
        format = "%a %Y-%m-%d %H:%M:%S"
}

load {
        format = "%1min"
}

cpu_temperature 0 {
	format = "%degrees°C"
	path = "/sys/class/hwmon/hwmon2/temp1_input"
}


disk "/home/fabian/data" {
	format = "d/%avail"
	low_threshold = 3
	threshold_type = percentage_avail
}

disk "/" {
	format = "/%avail"
	low_threshold = 5
	threshold_type = percentage_avail
}
