name: CI

on:
  push:

defaults:
  run:
    shell: nix develop --command bash -c "{0}"

jobs:
  build:
    runs-on: nix
    steps:
      - name: Initialize CI
        uses: https://git.qo.is/qo.is/actions-nix-init@main
        with:
          token: ${{ secrets.CI_TOKEN }}
          lfs: false

      - name: Setup Attic Cache
        env:
          CACHE_NAME: fabianhauser
          CACHE_REPOSITORY: fabianhauser:dotfiles
          SERVER: https://attic.qo.is/
          ATTIC_AUTH_TOKEN: ${{ secrets.ATTIC_AUTH_TOKEN }}
        run: |
          attic login "$CACHE_NAME" "$SERVER" "$ATTIC_AUTH_TOKEN"
          attic use "$CACHE_REPOSITORY"

      - name: Run Checks
        run: nix-fast-build --no-nom --max-jobs 1 --skip-cached --attic-cache fabianhauser:dotfiles
